print("1.count() method")
numbers=(10,20,30,40,30,60,30,20)
print("count is:",numbers.count(30))
print("\n-----------------")
print("2.Index() method")
numbers=(10,20,30,40,50)
print("Index is:",numbers.index(40))
print("\n------------------")
print("Code Executed Sucessfully----")
input("please click enter to exit")
